language: c

dist: xenial

compiler:
  - gcc

before_install:
  - curl http://apt.pilight.org/pilight.key | sudo apt-key add -
  - echo "deb http://apt.pilight.org/ stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install cmake dialog libwiringx libwiringx-dev libpcap0.8-dev libmbedtls-dev liblua5.2-dev libluajit-5.1-dev

script:
  - mkdir build && cd build && cmake ..
  - make -j4
  - sudo make install
